# .github/workflows/organize-papers.yml
name: Organize Papers

on:
  push:
    branches:
      - main  # Change to your default branch if different
    paths:
      - '**.pdf'
      - '**/'

jobs:
  organize_papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable automatic token usage

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyPDF2 requests

      - name: Run Organize Script
        run: python organize_papers.py

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Add Changes
        run: git add .

      - name: Commit Changes
        run: |
          git commit -m "Organized new papers" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
