name: Process PDF

on:
  push:
    paths:
      - "*.pdf"

jobs:
  process-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install PyPDF2 requests markdown

      - name: Process PDF and update README
        run: |
          python process_pdf.py
          
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with new PDF metadata"
          git push
